### ISSUE TITLE
Criar a Seção de Seguros da Bikcraft 

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#10]
@emmanuelmarcosdeoliveira 
Por favor dar inicio a seção de Seguros 

👀👀

**Comment by emmanuelmarcosdeoliveira** [comment]
OK

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 
#10


- [x] concluido !
- [x] Resposnisvo!

![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/a92d7301-487a-4e78-b1bb-9f7abd797e14)

**Comment by oliveira-emmanuel** [comment]
OK !

<details><summary>Details</summary>
<p>
Está perfeito!!</p>
</details>
