### ISSUE TITLE
Criar o Footer do Site Bikcraft

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#11]
@emmanuelmarcosdeoliveira 
Start Footer !!
go go go !!!!!

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 
- [x] Responsivida 👍
- [x] Finalizado!

![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/e684167b-95d5-4389-81fd-5686bd6b78a3)

**Comment by oliveira-emmanuel** [comment]
Ok!

**Comment by emmanuelmarcosdeoliveira** [comment]
OK
