### ISSUE TITLE
Criar a página Termos e Condições do Bikcraftr

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#12]
@emmanuelmarcosdeoliveira 
Inicar!

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 

- [x] Responsivo 👍
- [x] Conclúido 



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/94420d2c-10ea-4de3-b8ab-80fcd5355a6d)

**Comment by oliveira-emmanuel** [comment]
Ok !
