### ISSUE TITLE
Criar a página Biciletas do Projeto Bikcraft

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#13]
@emmanuelmarcosdeoliveira  
go go go !!!

@oliveira-emmanuel 
Verificar é dar um feedback

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 

Verificar 

- [x] Resposnivo 
- [x] Página Construida


![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/311f19cf-ffed-4d44-8ec9-c7eeff105463)



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/ad36f4d0-2fe0-4360-9fa9-521a09f7d75f)



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/cc5fe50b-ff26-407b-8a79-c0c4196ee8f7)

**Comment by oliveira-emmanuel** [comment]
Po de fechar e dar continuidade !!!
👌

**Comment by emmanuelmarcosdeoliveira** [comment]
Ok tanks !!
