### ISSUE TITLE
Bikcraft  - Biciletas Internas

### ISSUE THREAD

**Issue by emmanuelmarcosdeoliveira** [emmanuelmarcosdeoliveira/bikcraft#2]
Desenvolver a página de Bicicletas do Bikcraft e sua parte responsiva
@emmanuelmarcosdeoliveira 

abaixo link do figma
[figma](https://www.figma.com/file/VpnU0dQWEySgFPf5Tlm15z/bikcraft?type=design&node-id=8%3A3&t=jUM9QreCwUT2sohA-1)

![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/f055b8fb-9358-41b5-a1d1-83a2047f50c0)

**Comment by oliveira-emmanuel** [comment]
Ok irei dar o suporte necessário

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 
Os Detalhes estarei fazendo no final do projeto!


- [x] Página Construida ✅
- [x] Resnponsivo ✅
- [ ] Detalhes 👎

![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/5f4ae699-ca58-4bd4-a812-f1ae9400f396)



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/1f45ca2b-8768-42dc-8b75-10340d0861d6)



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/cf084489-171e-493a-a34e-59c86078ac07)
