### ISSUE TITLE
bicraft - Header - Menu

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#3]
Emmanuel hoje criar o menu da Home

**Comment by emmanuelmarcosdeoliveira** [comment]
Ok

**Comment by oliveira-emmanuel** [comment]
@emmanuelmarcosdeoliveira 

Após concluido me avisar que vou verificar

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 



![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/00eec5ba-b9d2-4088-b6c4-384aa3671ff6)

Menu concluido!!
