### ISSUE TITLE
Bikcraft - Desenvolver a parte de introdução do Menu

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#4]
@emmanuelmarcosdeoliveira 
Por favor desenvolver a área de introdução.

![image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/122749906/e52537b7-0411-48b4-8b8b-6e3a9b50566a)

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 
👍

**Comment by emmanuelmarcosdeoliveira** [comment]
- Introdução Concluido
- [x] Check

![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/3e7c802a-2037-468b-a06c-e75a5e75d8d2)
