### ISSUE TITLE
Criação da seção de tecnologias

### ISSUE THREAD

**Issue by emmanuelmarcosdeoliveira** [emmanuelmarcosdeoliveira/bikcraft#7]
> @oliveira-emmanuel 

Estou começando a seção de tecnologias.
Ao fina avaliar e dar um ok 

- [x] 👍

**Comment by emmanuelmarcosdeoliveira** [comment]
- [x] Concluido !!
@oliveira-emmanuel 

![image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/d38090ce-f0d9-4e44-bc64-593d24d9f638)

**Comment by oliveira-emmanuel** [comment]
Perfeito pode prosseguir!!
