### ISSUE TITLE
Seção Parceiros

### ISSUE THREAD

**Issue by emmanuelmarcosdeoliveira** [emmanuelmarcosdeoliveira/bikcraft#8]
### Dando incio a seção dos parceiros 
@oliveira-emmanuel 

- [x] ✅

**Comment by emmanuelmarcosdeoliveira** [comment]
- [x] Concluido ✅
- [x] Responsivo 👌
@oliveira-emmanuel 
Verificar 👀👀




![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/2e6413ef-a73c-49c4-8466-d243f2fbe220)

**Comment by oliveira-emmanuel** [comment]
Perfect  !

- [x] 👀✅

👋👋👋👋👋
