### ISSUE TITLE
Seção de Depoimentos

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/bikcraft#9]
### Secão de Depoimentos

@emmanuelmarcosdeoliveira  
Dar incio a seção de depoimentos

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 
Ok dando Inicio!!👍

https://github.com/emmanuelmarcosdeoliveira/bikcraft/issues/9

**Comment by emmanuelmarcosdeoliveira** [comment]
@oliveira-emmanuel 

- [x] Concluido
- [x] Responsividade 




![Image](https://github.com/emmanuelmarcosdeoliveira/bikcraft/assets/116108389/d1ea975d-d329-47b6-a5d6-9f74ad38e0fa)

**Comment by oliveira-emmanuel** [comment]
Ok Verifica está ok !
🎉😁
